### ISSUE TITLE
Fatal error if a value transient is an object

### ISSUE THREAD

**Issue by alvisir** [awesomemotive/Transients-Manager#10]
Hi,
if a value transient is an object, in 'value' column of the plugin table appears this fatal error:
Catchable fatal error: Object of class __PHP_Incomplete_Class could not be converted to string in xxxxxxxxx/wp-includes/formatting.php on line 3758

![error](https://cloud.githubusercontent.com/assets/3649824/4340306/bd1e9c94-402c-11e4-91d5-e139ce123d19.jpg)

**Comment by JJJ** [comment]
This has been addressed in version 2.0.

🙏
