### ISSUE TITLE
Auto-clean transients at selectable intervals

### ISSUE THREAD

**Issue by Stradders** [awesomemotive/Transients-Manager#45]
Would it be possible to add an auto clean option please? Perhaps with a selectable interval and option to delete all/expired etc? Thanks

**Comment by JJJ** [comment]
If I understand this request correctly, I believe there exists a plugin that will already do a great job at this:

https://wordpress.org/plugins/wp-crontrol/

We've added the ability in 2.0 to delete all/expired/expirable/persistent transients, but not at a specified time.

For that, you probably want a task runner/scheduler, and the above plugin provides a UI for WordPress Cron, which I think will help visualize that kind of scheduling.

Thank you @Stradders for the request, and for using Transients Manager. 🙏
