### ISSUE TITLE
Add bulk actions

### ISSUE THREAD

**Issue by evertiro** [awesomemotive/Transients-Manager#5]
It's probably not something that'd be commonly used, but my first use of Transients Manager involved needing to delete four separate transients... bulk actions would be REALLY nice, at least in terms of deleting and updating expirations.

**Comment by JJJ** [comment]
In 2.0, the buttons/forms have been moved to Bulk Actions dropdowns on the top/bottom of the List Table.

<img width="292" alt="jjj-on-2021-12-15-at-15-05-02@2x" src="https://user-images.githubusercontent.com/88951/146264840-8b9466ae-313a-47d5-aaaf-d0e076f7e888.png">

There are no plans to add inline/bulk editing/updating of Transients at this time.
