### ISSUE TITLE
Suspend Transients in WP admin bar is shifted under the admin bar with small screen size

### ISSUE THREAD

**Issue by Mai-Saad** [awesomemotive/Transients-Manager#54]
Precondition: 
- Open WP admin dashboard in small screen size i.e 1024 x 768
- Multiple plugins that appear in the admin bar are installed and activated

Steps:
1- install transients manager plugin 
2- activate the plugin

expected:
suspend transients exist in the admin bar
actual:
suspend transients and account are shifted under the admin bar

![transients](https://user-images.githubusercontent.com/76941962/107142242-1e27b000-6936-11eb-8016-6a04d43ebc5d.jpg)

**Comment by JJJ** [comment]
Hello @Mai-Saad 👋 Thank you for creating this issue here 🙏

I believe it may be better to address this problem & behavior in WordPress itself, and it is being tracked here: https://core.trac.wordpress.org/ticket/44438

Thank you again! 🙏
