### ISSUE TITLE
Warning on plugin page in admin

### ISSUE THREAD

**Issue by seredniy** [awesomemotive/Transients-Manager#60]
![image](https://user-images.githubusercontent.com/11270429/146782967-d2f6fd14-03e2-4b58-aa94-2e860d3180cd.png)

PHP 7.4

**Comment by seredniy** [comment]
I think it's related to https://github.com/awesomemotive/Transients-Manager/issues/59. In this case, please, close this issue as duplicated

**Comment by JJJ** [comment]
Thanks @seredniy 👍
